### ISSUE TITLE
PA Review: Stories

### ISSUE THREAD

**Issue by ajdelossantos** [ajdelossantos/Abstract#4]
- [x] Backend: DB. model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by ajdelossantos** [comment]
Pushed deadline into Saturday, which was my original intent.

**Comment by LochandQuay** [comment]
@ajdelossantos 
Looks like I'm assigned to this, but you haven't checked off the boxes? Is this ready for review?

**Comment by ajdelossantos** [comment]
It is not yet. I'll take you off the issue and get back to you. Feel free to reach out to me. Basically, I vastly underestimated the amount of code I needed to get right to implement this feature as intended. I'll let you know where I am by end of day.

**Comment by ajdelossantos** [comment]
I'll seed the database further later tonight.

**Comment by LochandQuay** [comment]
@ajdelossantos 

WOW! This looks really clean. Just a few small comments:
- [ ] On your story index items, the images go like two pixels below the box they're in. This is because you have the index item div set to `box-sizing: border-box`. This is a rare case where you actually would want the box sizing to be `content-box`, so the border goes around the image, instead of the image covering it up.
- [ ] Add delete/edit story buttons for the author on the story display page.

**Comment by ajdelossantos** [comment]
Made a push to Heroku. I'll implement image preview if there's time later.

**Comment by LochandQuay** [comment]
@ajdelossantos 

Console Errors: 
- [ ] You have a typo somewhere: Invalid DOM property `classname`. Did you mean `className`? (hit after logging in and clicking on a story...probably somewhere in your comments components)

Functionality Issues:
- [ ] When deleting a story from the story page, it should redirect back to the user's story index.

Styling Issues:
- [ ] On the user's story index, it looks like the edit/delete buttons are supposed to be attached to the story card, but they're slightly off.
