### ISSUE TITLE
PA Review: Commenting on stories

### ISSUE THREAD

**Issue by ajdelossantos** [ajdelossantos/Abstract#5]
- [x] Backend: DB, model, controller, views
    + Updated API calls to separate story and comment concerns
- [x] Redux Loop: ajax, actions, reducer
     + Refactoring redux cycle to handle AJAX
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by ajdelossantos** [comment]
It's ready for review. I'll begin work on Likes and seed this later.

**Comment by LochandQuay** [comment]
@ajdelossantos 

Looks good! I haven't been able to find major errors besides the typo on `className`.

I'll take this time then to Suggest that you start adding in `scrollTo(0, 0)` to some of your `componentDidMounts`. The reason for this is since it's a single page app, when you scroll down the index and click on a story, the page doesn't refresh, so you end up scrolled in partway through the story. Using `window.scrollTo(0, 0)` should fix that. :)

**Comment by ajdelossantos** [comment]
Changes implemented as requested. Ready for review.
